trigger:
- master

variables:
  nodeVersion: '12.x'
  workingDir: 'IoTEdgeSolution/modules/MachineTemperatureFilter'
  azureSubscription: 'AzureSubscriptionServiceConnection'
  azureContainerRegistryName: 'adhoc23acr' # TODO: replace with '{your-acr-name}'
  azureIotHubName: 'adhoc23-iothub' # TODO: replace with '{your-iothub-name}'

stages:
  - stage: 'Test'
    displayName: 'Build npm and Test IoT module'
    jobs:
      - job: 'Test'
        displayName: 'Build and unit tests'
        pool:
          vmImage: 'ubuntu-16.04'
          demands:
            - npm
        steps:
          - task: NodeTool@0
            displayName: 'Use Node 12.x'
            inputs:
              versionSpec: '$(nodeVersion)'
          - task: Npm@1
            displayName: 'Install Dependences'
            inputs:
              workingDir: '$(workingDir)'
              verbose: false
          - task: Npm@1
            displayName: 'Run UnitTest'
            inputs:
              command: custom
              workingDir: '$(workingDir)'
              verbose: false
              customCommand: test

  - stage: 'BuildAndPushImage'
    displayName: 'Build and Push IoT module image'
    dependsOn: 'Test'
    condition: 'succeeded()'
    jobs:
      - job: 'BuildAndPushImage'
        displayName: 'Build and Push IoT module image'
        pool:
          vmImage: 'ubuntu-16.04'
        steps:
          - task: AzureCLI@1
            displayName: 'Azure CLI: Get ACR credentials'
            inputs:
              azureSubscription: '$(azureSubscription)'
              scriptLocation: inlineScript
              inlineScript: |
                if [ -z "${ACR_USER}" ]; then
                    ACR_USER=$(az acr credential show -n "${azureContainerRegistryName}" --query username) && \
                    ACR_USER=${ACR_USER//\"/} && \
                    ACR_PASSWORD=$(az acr credential show -n "${azureContainerRegistryName}" --query passwords[0].value) && \
                    ACR_PASSWORD=${ACR_PASSWORD//\"/} && \
                    ACR_ADDRESS=$(az acr show -n "${azureContainerRegistryName}" --query loginServer) && \
                    ACR_ADDRESS=${ACR_ADDRESS//\"/}
                fi && \
                echo "##vso[task.setvariable variable=ACR_USER]${ACR_USER}" && \
                echo "##vso[task.setvariable variable=ACR_PASSWORD]${ACR_PASSWORD}" && \
                echo "##vso[task.setvariable variable=ACR_ADDRESS]${ACR_ADDRESS}"
          - task: AzureIoTEdge@2
            displayName: 'AzureIoTEdge - Build module images'
            inputs:
              action: 'Build module images'
              templateFilePath: deployment.template.json
              defaultPlatform: amd64
          - task: AzureIoTEdge@2
            displayName: 'AzureIoTEdge - Push module images'
            inputs:
              action: 'Push module images'
              azureSubscriptionEndpoint: '$(azureSubscription)'
              containerregistrytype: 'Azure Container Registry'
              azureContainerRegistry: '$(azureContainerRegistryName)'
              templateFilePath: deployment.template.json
              defaultPlatform: amd64
              fillRegistryCredential: false
